# Generated by Django 6.0.6 on 2026-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talisman_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks for the transaction.', null=True),
        ),
    ]
